version: '3.8'

services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "5001"
    environment:
      - FLASK_ENV=development
      - APP_CONFIG_FILE=/app/app/config.py
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
      POSTGRES_DB: flask_app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
